Repository redcanaryco/atomic-red-team, pull requests merged in 2020-10, with the labels that each got.

#1237 Add tests for T1070.003 Clear Command History
  atomics/T1070.003/T1070.003.yaml
Labels: windows

#1242 Added tests for T1098.004.
  atomics/T1098.004/T1098.004.yaml
Labels: linux, macOS

#1241 Added MacOS tests for T1115
  atomics/T1115/T1115.yaml
Labels: macOS

#1236 Add tests for T1134.001 Access Token Impersonation/Theft
  atomics/T1134.001/T1134.001.yaml
Labels: windows

#1247 update/clarify description
  atomics/Indexes/index.yaml
  atomics/T1197/T1197.md
  atomics/T1197/T1197.yaml
Labels: windows

#1246 [OSCD] Tests added for T1497.001
  atomics/T1497.001/T1497.001.yaml
Labels: linux, macOS, windows

#1262 [OSCD] Update T1564.002: Hidden User Creation test for macOS
  atomics/T1564.002/T1564.002.yaml
Labels: macOS

#1263 [OSCD] updated a few tests
  atomics/T1553.001/T1553.001.yaml
  atomics/T1562.001/T1562.001.yaml
Labels: linux, macOS

#1268 [OSCD] Added T1562.006 tests to emulate indicator blocking on Linux
  atomics/T1562.006/T1562.006.yaml
Labels: linux
