Repository redcanaryco/atomic-red-team, pull requests merged in 2020-11, with the labels that each got.

#1264 [OSCD] Adding T1547.010
  atomics/T1547.010/T1547.010.yaml
Labels: windows

#1267 [OSCD] split Linux and macOS tests for T1518.001; update processes list
  atomics/T1518.001/T1518.001.yaml
Labels: linux, macOS

#1300 Expand cronjob tests
  atomics/T1053.003/T1053.003.yaml
Labels: linux

#1299 Add two T1003.008 tests
  atomics/T1003.008/T1003.008.md
  atomics/T1003.008/T1003.008.yaml
Labels: linux
