Repository redcanaryco/atomic-red-team, pull requests merged in 2021-06, with the labels that each got.

#1488 Atomic Tests for T1543.002 : Ubuntu, CentOS, Kali
  atomics/T1543.002/T1543.002.md
Labels: linux

#1486 Add test for T1037.004 that modifies rc.local and rc.common files on …
  atomics/T1037.004/T1037.004.yaml
  atomics/T1137.004/T1137.004.md
Labels: linux

#1489 T1552.001 : Find and Access unsecured credentials in file - GitHub access token
  atomics/T1552.001/T1552.001.md
  atomics/T1552.001/T1552.001.yaml
Labels: linux, macOS

#1499 T1543.002 : systemd create service modify service linux
  atomics/T1543.002/T1543.002.yaml
Labels: linux

#1498 adding kubectl to spec
  atomic_red_team/atomic_red_team.rb
  atomic_red_team/spec.yaml
Labels: cloud

#1506 Create T1553.005 Atomic Test
  atomics/T1553.005/T1553.005.md
  atomics/T1553.005/T1553.005.yaml
  atomics/T1553.005/src/T1553.005.iso
Labels: windows

#1508 New Dump credentials from Windows Credential Manager With PowerShell …
  atomics/T1555/T1555.yaml
Labels: windows

#1505 T1003.007: OS Credential Dumping: Proc Filesystem
  atomics/T1003.007/T1003.007.yaml
  atomics/T1003.007/src/dump_heap.py
Labels: linux

#1504 T1110.004 : SSH Credential Stuffing FROM Linux , MacOS
  atomics/T1110.004/T1110.004.yaml
  atomics/T1110.004/src/credstuffuserpass.txt
Labels: linux, macOS

#1507 T1036.005: Masquerading: Match Legitimate Name or Location
  atomics/T1036.005/T1036.005.yaml
Labels: linux, macOS

#1515 Amend regkey path for Macro security level
  atomics/T1137/T1137.md
  atomics/T1137/T1137.yaml
Labels: windows

#1510 Added 'whois file download' test to T1105
  atomics/T1105/T1105.yaml
Labels: linux, macOS

#1521 name update
  atomics/T1564/T1564.yaml
Labels: windows

#1524 add note about secure boot
  atomics/T1546.010/T1546.010.yaml
Labels: windows

#1523 don't disable rdp during cleanup by default
  atomics/T1078.001/T1078.001.yaml
Labels: windows

#1527 T1072
  atomics/T1072/T1072.yaml
Labels: windows

#1457 AWS Cloud atomics
  .gitignore
  atomics/T1098.001/T1098.001.yaml
  atomics/T1098.001/bin/aws_secret.sh
  atomics/T1098/T1098.yaml
  atomics/T1136.003/T1136.003.yaml
Labels: cloud

#1535 Update T1197.yaml
  atomics/T1197/T1197.yaml
Labels: windows
