Repository redcanaryco/atomic-red-team, pull requests merged in 2021-08, with the labels that each got.

#1586 Added T1204.002 Test 9 for Generic Payload Download
  atomics/T1204.002/T1204.002.yaml
  atomics/T1204.002/src/test9-GenericPayloadDownload.txt
  atomics/T1204.002/src/test9-example-payload.txt
Labels: windows

#1525 added GnuPG to T1552.004 & tidyup
  atomics/T1552.004/T1552.004.yaml
Labels: linux, macOS

#1528 T1140 Deobfuscate/Decode Files or Information: Extended tests
  atomics/T1140/T1140.yaml
Labels: linux, macOS

#1537 T1562.004 deleted 1 added 9
  atomics/T1562.004/T1562.004.yaml
Labels: linux

#1563 fix(T1222.002): recursive chmod and chown for macos
  atomics/T1222.002/T1222.002.yaml
Labels: linux, macOS

#1597 Automated AWS cloudtrail changes
  atomics/T1562.008/T1562.008.yaml
  atomics/T1562.008/src/policy.json
Labels: cloud

#1605 T1552.004: ADFS Certificates theft
  atomics/T1552.004/T1552.004.yaml
Labels: windows, ADFS
