Repository redcanaryco/atomic-red-team, pull requests merged in 2021-07, with the labels that each got.

#1540 moving invoke-maldoc into art repo
  atomics/T1053.005/T1053.005.yaml
  atomics/T1055.012/T1055.012.yaml
  atomics/T1055/T1055.yaml
  atomics/T1059.005/T1059.005.yaml
  atomics/T1070.001/T1070.001.yaml
  atomics/T1115/T1115.yaml
  atomics/T1204.002/T1204.002.yaml
  atomics/T1204.002/src/Invoke-MalDoc.ps1
  atomics/T1555/T1555.yaml
  atomics/T1564/T1564.yaml
  atomics/T1566.001/T1566.001.yaml
Labels: windows

#1483 T1110.003 azureadaccounts
  atomics/T1110.003/T1110.003.yaml
Labels: cloud

#1482 T1110.001 azureadaccounts
  atomics/T1110.001/T1110.001.yaml
Labels: cloud

#1454 T1098.001: implement AAD application hijacking tests
  atomics/T1098.001/T1098.001.yaml
Labels: cloud

#1548 fix cleanup cmd as per issue #1543
  atomics/T1136.002/T1136.002.yaml
Labels: windows

#1546 Convert 'kubectl' tests to "Containers" as Platform
  atomics/T1053.007/T1053.007.yaml
  atomics/T1552.007/T1552.007.yaml
  atomics/T1609/T1609.yaml
Labels: containers

#1545 Update Platform in T1611 to "containers"
  atomics/T1611/T1611.yaml
Labels: containers

#1577 add domain joined check
  atomics/T1558.003/T1558.003.yaml
Labels: windows

#1575 fix cleanup command
  atomics/T1053.005/T1053.005.yaml
Labels: windows

#1576 update mimikatz download URL
  atomics/T1550.002/T1550.002.yaml
Labels: windows
