Repository redcanaryco/atomic-red-team, pull requests merged in 2022-10, with the labels that each got.

#2081 fixes #2080: macos audio recording
  atomics/T1123/T1123.md
  atomics/T1123/T1123.yaml
  atomics/T1123/src/T1123.sh
Labels: macOS

#2099 T1201_Improved
  atomics/T1201/T1201.yaml
Labels: linux

#2194 fix dir creation
  atomics/T1505.003/T1505.003.yaml
Labels: windows

#2200 Tccontre patch 1
  atomics/T1016/T1016.yaml
Labels: windows

#2196 T1547.004 new hklm tests
  atomics/T1547.004/T1547.004.yaml
Labels: windows

#2197 AWS - Password Spray an AWS using GoAWSConsoleSpray
  atomics/T1110.003/T1110.003.yaml
  atomics/T1110.003/src/aws_passwords.txt
  atomics/T1110.003/src/aws_users.txt
Labels: cloud

#2207 New AutoDial DLL persistence atomic
  atomics/T1546/T1546.yaml
  atomics/T1546/bin/AltWinSock2DLL.dll
  atomics/T1546/src/AltWinSock2DLL.sln
  atomics/T1546/src/AltWinSock2DLL/AltWinSock2DLL.cpp
  atomics/T1546/src/AltWinSock2DLL/AltWinSock2DLL.vcxproj
  atomics/T1546/src/AltWinSock2DLL/AltWinSock2DLL.vcxproj.filters
  atomics/T1546/src/AltWinSock2DLL/AltWinSock2DLL.vcxproj.user
Labels: windows

#2203 add dependency executor since it is different than attack cmds
  atomics/T1546.007/T1546.007.yaml
Labels: windows

#2210 fix missing input arg
  atomics/T1546/T1546.yaml
Labels: windows

#2202 Updated T1048.003 to include Rclone
  atomics/T1048.003/T1048.003.yaml
Labels: windows
