Repository redcanaryco/atomic-red-team, pull requests merged in 2022-02, with the labels that each got.

#1748 T1098 - adding user and service principal to both Azure AD role and Azure role.
  atomics/T1098/T1098.md
  atomics/T1098/T1098.yaml
Labels: cloud

#1766 Command and Scripting Interpreter: Bash - 2 new atomics
  atomics/T1059.004/T1059.004.yaml
Labels: linux

#1771 Psiphon
  atomics/T1090.003/T1090.003.yaml
  atomics/T1090.003/src/Psiphon.bat
Labels: windows

#1778 DiskShadow Execution of script
  atomics/T1218/T1218.yaml
  atomics/T1218/src/T1218.txt
Labels: windows
