Repository redcanaryco/atomic-red-team, pull requests merged in 2022-08, with the labels that each got.

#2061 Add 2 New Atomics - T2562.008
  atomics/T1562.008/T1562.008.yaml
Labels: cloud

#2054 3 new aws stratus atomics
  atomics/T1562.008/T1562.008.yaml
Labels: cloud

#2052 Linux rootkits
  atomics/T1014/T1014.yaml
Labels: linux

#2068 Adding T1552.005 Test 2 - Azure - Dump Azure Instance Metadata from Virtual Machines
  atomics/T1552.005/T1552.005.yaml
Labels: cloud

#2071 Update T1083 to add new test
  atomics/T1083/T1083.yaml
Labels: windows

#2077 T1530: Anonymous Access to AWS S3
  atomics/T1530/T1530.yaml
  atomics/T1530/src/policy.json
Labels: cloud

#2076 T1619 Cloud Storage Object Discovery
  atomics/T1619/T1619.yaml
Labels: cloud

#2088 AWS - Retrieve EC2 Password Data using stratus
  atomics/T1552/T1552.yaml
Labels: cloud

#2082 Create T1528 Test 1 - Dump All Azure Key Vaults with Microburst
  atomics/T1528/T1528.yaml
Labels: cloud

#2083 T1219 update
  atomics/T1219/T1219.yaml
Labels: windows

#2090 T1555.003 Browser stealer
  atomics/T1555.003/T1555.003.yaml
  atomics/T1555.003/bin/BrowserCollector.exe
  atomics/T1555.003/src/Login Data
Labels: windows
