Repository redcanaryco/atomic-red-team, pull requests merged in 2022-06, with the labels that each got.

#1983 Create T1611.002.yaml "Escape to Host"
  atomics/T1611.002/T1611.002.yaml
Labels: cloud

#1989 Added T1574.006 MacOS Dylib Injection
  atomics/T1574.006/T1574.006.yaml
  atomics/T1574.006/src/MacOS/T1574.006.c
Labels: macOS

#2002 New test using TruffleSnout.exe/typo
  README.md
  atomics/T1482/T1482.yaml
Labels: windows

#1995 Adding T1530 Test 1 - Enumerate Azure Blobs with MicroBurst
  atomics/T1530/T1530.yaml
Labels: cloud

#2012 Updated T1027 i0 with cleanup and non-builtin command
  atomics/T1027/T1027.yaml
Labels: linux

#1994 Python pty module and spawn function used to spawn sh or bash
  atomics/T1059.006/T1059.006.yaml
Labels: linux
