Repository redcanaryco/atomic-red-team, pull requests merged in 2022-11, with the labels that each got.

#2219 Added missing test for T1547.014 Active Setup, 3 tests created
  atomics/T1547.014/T1547.014.yaml
Labels: windows

#2195 Fix T1546.004 for remote execution on Linux
  atomics/T1546.004/T1546.004.yaml
Labels: linux

#2211 Add macOS T1547.015 add/remove LoginItem via AppleScript
  atomics/T1547.015/T1547.015.yaml
  atomics/T1547.015/src/add_login_item.osa
  atomics/T1547.015/src/remove_login_item.osa
Labels: macOS

#2223 Move 2 atomics from 1547.001 to 1546 as a better fit
  atomics/T1059.001/T1059.001.yaml
  atomics/T1112/T1112.yaml
  atomics/T1546/T1546.yaml
  atomics/T1547.001/T1547.001.yaml
  atomics/T1548.002/T1548.002.yaml
Labels: windows

#2217 Add T1547.006 kernel module load and unload tests for MacOS
  atomics/T1547.006/T1547.006.yaml
  atomics/T1547.006/src/macos_kextload.c
Labels: macOS

#2220 Add two MacOS T1547.007 loginwindow reopen tests
  atomics/T1547.007/T1547.007.yaml
  atomics/T1547.007/src/append_reopen_loginwindow.m
  atomics/T1547.007/src/reopen_loginwindow_calc.plist
Labels: macOS

#2230 HiveNightmare simplifications
  atomics/T1003.002/T1003.002.yaml
Labels: windows

#2213 Add Linux T1040 Packet Capture using raw sockets and filtering
  atomics/T1040/T1040.yaml
  atomics/T1040/src/linux_pcapdemo.c
Labels: linux

#2231 Use AADInternals for AAD federation attack
  atomics/T1484.002/T1484.002.yaml
Labels: cloud
