Repository redcanaryco/atomic-red-team, pull requests merged in 2023-06, with the labels that each got.

#2427 Add new atomic test to T1140.yaml
  atomics/T1140/T1140.yaml
Labels: linux, macOS

#2369 update T1562.004 with more commands
  atomics/T1562.004/T1562.004.yaml
Labels: linux

#2432 Update T1562.008.yaml
  atomics/T1562.008/T1562.008.yaml
Labels: cloud

#2437 Update T1078.004
  atomics/T1078.004/T1078.004.yaml
  atomics/T1078.004/src/T1078.004-2/T1078.004-2.tf
  atomics/T1078.004/src/T1078.004-2/terraform.tfvars
Labels: cloud

#2455 adding new test in T1176 - Load unpacked extension with command line
  atomics/T1176/T1176.yaml
Labels: windows

#2451 No need to export the PFX to get the public certificate, so removed it
  atomics/T1098.001/T1098.001.yaml
Labels: cloud

#2452 parameterize T1070.002 tests
  atomics/T1070.002/T1070.002.yaml
Labels: macOS

#2396 Added 3 new tests - macOS T1486
  atomics/T1486/T1486.yaml
Labels: macOS, windows

#2460 use ExternalPayloads directory
  atomics/T1003.001/T1003.001.yaml
  atomics/T1003.002/T1003.002.yaml
  atomics/T1003.004/T1003.004.yaml
  atomics/T1021.002/T1021.002.yaml
  atomics/T1021.006/T1021.006.yaml
  atomics/T1027/T1027.yaml
  atomics/T1040/T1040.yaml
  atomics/T1046/T1046.yaml
  atomics/T1047/T1047.yaml
  atomics/T1048.002/T1048.002.yaml
  atomics/T1048/T1048.yaml
  atomics/T1055/T1055.yaml
  atomics/T1059.003/T1059.003.yaml
  atomics/T1069.001/T1069.001.yaml
  atomics/T1070.006/T1070.006.yaml
  atomics/T1071.001/T1071.001.yaml
  atomics/T1072/T1072.yaml
  atomics/T1082/T1082.yaml
  atomics/T1083/T1083.yaml
  atomics/T1087.002/T1087.002.yaml
  atomics/T1090.003/T1090.003.yaml
  atomics/T1095/T1095.yaml
  atomics/T1105/T1105.yaml
  atomics/T1110.001/T1110.001.yaml
  atomics/T1110.002/T1110.002.yaml
  atomics/T1110.003/T1110.003.yaml
  atomics/T1110.004/T1110.004.yaml
  atomics/T1133/T1133.yaml
  atomics/T1134.001/T1134.001.yaml
  atomics/T1134.005/T1134.005.yaml
  atomics/T1135/T1135.yaml
  atomics/T1187/T1187.yaml
  atomics/T1207/T1207.yaml
  atomics/T1219/T1219.yaml
  atomics/T1482/T1482.yaml
  atomics/T1485/T1485.yaml
  atomics/T1486/T1486.yaml
  atomics/T1526/T1526.yaml
  atomics/T1528/T1528.yaml
  atomics/T1530/T1530.yaml
  atomics/T1539/T1539.yaml
  atomics/T1546.015/T1546.015.yaml
  atomics/T1547.008/T1547.008.yaml
  atomics/T1548.002/T1548.002.yaml
  atomics/T1550.003/T1550.003.yaml
  atomics/T1555.003/T1555.003.yaml
  atomics/T1558.001/T1558.001.yaml
  atomics/T1558.002/T1558.002.yaml
  atomics/T1558.003/T1558.003.yaml
  atomics/T1558.004/T1558.004.yaml
  atomics/T1560.001/T1560.001.yaml
  atomics/T1562.001/T1562.001.yaml
  atomics/T1562.006/T1562.006.yaml
  atomics/T1564.006/T1564.006.yaml
  atomics/T1567.002/T1567.002.yaml
  atomics/T1569.002/T1569.002.yaml
Labels: windows

#2462 use ExternalPayloads folder
  atomics/T1003/T1003.yaml
  atomics/T1049/T1049.yaml
  atomics/T1059.001/T1059.001.yaml
  atomics/T1105/T1105.yaml
  atomics/T1218/T1218.yaml
  atomics/T1220/T1220.yaml
  atomics/T1552.004/T1552.004.yaml
  atomics/T1552.006/T1552.006.yaml
  atomics/T1559/T1559.yaml
  atomics/T1569.002/T1569.002.yaml
  atomics/T1569.002/bin/PsExec.exe
Labels: windows

#2464 move adfind to external resource
  atomics/T1016/T1016.yaml
  atomics/T1018/T1018.yaml
  atomics/T1069.002/T1069.002.yaml
  atomics/T1087.002/T1087.002.yaml
  atomics/T1087.002/src/AdFind.exe
  atomics/T1482/T1482.yaml
Labels: linux, windows

#2458 Add T1036.004 linux test rename process comm using prctl PR_SET_NAME
  atomics/T1036.004/T1036.004.yaml
  atomics/T1036.004/src/prctl_rename.c
Labels: linux

#2457 Add GCP Atomics
  atomics/T1078.004/T1078.004.yaml
  atomics/T1098/T1098.yaml
  atomics/T1098/src/T1098-17/T1098-17.tf
  atomics/T1098/src/T1098-17/terraform.tfvars
  atomics/T1485/T1485.yaml
  atomics/T1485/src/T1485-4/T1485-4.tf
  atomics/T1485/src/T1485-4/terraform.tfvars
  atomics/T1562.008/T1562.008.yaml
Labels: cloud

#2468 Added Linux Tests to T1069.002, T1087.002, T1136.002
  atomics/T1069.002/T1069.002.yaml
  atomics/T1087.002/T1087.002.yaml
  atomics/T1136.002/T1136.002.yaml
Labels: linux

#2469 Add T1539 macOS Chrome Remote Debugging
  atomics/T1539/T1539.yaml
Labels: macOS

#2472 Create T1562.009.yaml with "Impair Defenses - Safe Boot Mode"
  atomics/T1562.009/T1562.009.yaml
Labels: windows

#2473 New atomic Test - Driver Enumeration using driverquery
  atomics/T1082/T1082.yaml
Labels: windows

#2475 AMSI COM
  atomics/T1562.001/T1562.001.yaml
Labels: windows
