Repository redcanaryco/atomic-red-team, pull requests merged in 2023-11, with the labels that each got.

#2584 New Atomic - T1654 Log Enumeration
  atomics/T1654/T1654.yaml
Labels: windows

#2593 fix link
  atomics/T1654/T1654.yaml
Labels: windows

#2587 Process injection RWX injection / Mockingjay local injection
  atomics/T1055/T1055.yaml
  atomics/T1055/bin/x64/RWXinjectionLocal.exe
  atomics/T1055/bin/x64/searchVuln.exe
  atomics/T1055/bin/x64/vuln_dll/msys-2.0.dll
  atomics/T1055/src/x64/RWXInjection/build.bat
  atomics/T1055/src/x64/RWXInjection/path_finder.c
  atomics/T1055/src/x64/RWXInjection/rwx_local.c
Labels: windows

#2588 Add Test for Registry-Only "Ghost Tasks" Procedure within T1053.005
  atomics/T1053.005/T1053.005.yaml
Labels: windows

#2582 New Atomic - Excel Application Object for LM
  atomics/T1021.003/T1021.003.md
  atomics/T1021.003/T1021.003.yaml
Labels: windows

#2596 Update T1218.yaml
  atomics/T1218/T1218.yaml
Labels: windows

#2597 Incorrect Dependency Executor on T1218,12.yaml
  atomics/T1218/T1218.yaml
Labels: windows

#2595 ignore certificate
  atomics/T1048.002/T1048.002.yaml
Labels: windows

#2402 T1005 Find and dump sqlite databases (Linux)
  atomics/T1005/T1005.yaml
  atomics/T1005/src/art
  atomics/T1005/src/gta.db
  atomics/T1005/src/sqlite_dump.sh
Labels: linux

#2603 FreeBSD Cleanup
  atomics/T1003.008/T1003.008.yaml
  atomics/T1007/T1007.yaml
  atomics/T1016/T1016.yaml
  atomics/T1027/T1027.yaml
  atomics/T1036.006/T1036.006.yaml
  atomics/T1037.004/T1037.004.yaml
  atomics/T1046/T1046.yaml
  atomics/T1048.003/T1048.003.yaml
  atomics/T1053.002/T1053.002.yaml
  bin/generate_labels.py
Labels: linux, macOS

#2599 Added new test that tampers with windows defender registry
  atomics/T1562.001/T1562.001.yaml
Labels: windows

#2601 Add T1055.015 listPlanting test
  atomics/T1055.015/T1055.015.md
  atomics/T1055.015/T1055.015.yaml
  atomics/T1055.015/bin/listPlanting.exe
  atomics/T1055.015/src/build.bat
  atomics/T1055.015/src/listPlanting.c
Labels: windows

#2602 New LocalAdmin Persistence Technique
  atomics/T1136.001/T1136.001.yaml
Labels: windows

#2608 Added test for T1070.006 - Timestomp for date modified using SetFile on MacOS
  atomics/T1070.006/T1070.006.yaml
Labels: macOS

#2604 FreeBSD cleanup
  atomics/T1059.004/T1059.004.yaml
  atomics/T1070.003/T1070.003.yaml
  atomics/T1070.004/T1070.004.yaml
  atomics/T1074.001/T1074.001.yaml
  atomics/T1078.003/T1078.003.yaml
  atomics/T1087.001/T1087.001.yaml
  atomics/T1090.003/T1090.003.yaml
Labels: linux, macOS, windows

#2611 Lsass memory dump via SilentProcessExit technique
  atomics/T1003.001/T1003.001.yaml
Labels: windows

#2620 Add test for keychain dump
  atomics/T1555.001/T1555.001.yaml
Labels: macOS

#2622 Validator changes
  bin/validate/atomic-red-team.schema.yaml
  bin/validate/validate.py
  poetry.lock
  pyproject.toml
Labels: bug

#2624 Cleanup docs
  atomic_red_team/attack_api.rb
Labels: bug

#2621 Reorganization
  atomics/T1555.001/T1555.001.yaml
Labels: macOS

#2605 Adding T1087.002 Test - Ldapdomaindump on Linux
  atomics/T1087.002/T1087.002.yaml
Labels: linux
