Repository redcanaryco/atomic-red-team, pull requests merged in 2023-05, with the labels that each got.

#2388 Added 3 new tests - macOS & Linux T1531
  atomics/T1531/T1531.yaml
Labels: linux, macOS

#2303 Atomic Red Team - JSON Schema Validation CI
  .github/workflows/validate-atomics.yml
  atomics/T1040/T1040.yaml
  atomics/T1048.003/T1048.003.yaml
  atomics/T1055.001/T1055.001.yaml
  atomics/T1059.003/T1059.003.yaml
  atomics/T1059.004/T1059.004.yaml
  atomics/T1078.004/T1078.004.yaml
  atomics/T1087.002/T1087.002.yaml
  atomics/T1110.001/T1110.001.yaml
  atomics/T1113/T1113.yaml
  atomics/T1136.003/T1136.003.yaml
  atomics/T1137.004/T1137.004.yaml
  atomics/T1187/T1187.yaml
  atomics/T1486/T1486.yaml
  atomics/T1531/T1531.yaml
  atomics/T1543.003/T1543.003.yaml
  atomics/T1548.002/T1548.002.yaml
  atomics/T1552.001/T1552.001.yaml
  atomics/T1572/T1572.yaml
  atomics/T1611/T1611.yaml
  bin/validate-atomics.rb
  bin/validate/README.md
  bin/validate/atomic-red-team.schema.yaml
  bin/validate/validate.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#2428 Add a new atomic test to T1560.001.yaml
  atomics/T1560.001/T1560.001.yaml
Labels: linux, macOS

#2436 Update T1135.yaml - network share discovery via dir cmd
  atomics/T1135/T1135.yaml
Labels: windows

#2438 Auto labeling bugfix
  bin/generate_labels.py
  bin/validate/validate.py
Labels: bug

#2440 Password policy checks
  atomics/T1098/T1098.yaml
Labels: windows

#2445 Adding atomics to emulate suspicious LAPS attribute queries
  atomics/T1087.002/T1087.002.yaml
Labels: windows

#2447 New test under T1027: Executing zipped JavaScript using WScript
  atomics/T1027/T1027.yaml
  atomics/T1027/bin/t1027js.zip
Labels: windows
