Repository redcanaryco/atomic-red-team, pull requests merged in 2023-03, with the labels that each got.

#2351 added a new test for base64 encoded shebang shells
  atomics/T1140/T1140.yaml
Labels: linux, macOS

#2353 T1140 bash base64 decode
  atomics/T1140/T1140.yaml
Labels: linux

#2352 GK atomic red team t1136.003 update
  atomics/T1136.003/T1136.003.yaml
Labels: cloud

#2359 Gk atomic red team t1136.003 azure cli
  atomics/T1136.003/T1136.003.yaml
Labels: cloud

#2355 Azure persistence automation runbook created or modified
  atomics/T1078.004/T1078.004.yaml
Labels: cloud

#2321 Added 3 new tests T1078.003 - macOS
  atomics/T1078.003/T1078.003.yaml
Labels: macOS

#2364 T098: accept UserPrincipalName for the "user_principal_name" argument
  atomics/T1098/T1098.yaml
Labels: cloud

#2365 update T1012 with more commands
  atomics/T1012/T1012.yaml
Labels: windows

#2362 Gk atomic red team t1531 account deletion
  atomics/T1531/T1531.yaml
Labels: cloud

#2333 Added new tests - T1070.002 (macOS and Linux)
  atomics/T1070.002/T1070.002.yaml
Labels: linux, macOS

#2334 Added new tests (T1562) - macOS
  atomics/T1562/T1562.yaml
Labels: linux
