Repository redcanaryco/atomic-red-team, pull requests merged in 2023-08, with the labels that each got.

#2503 Tccontre max connection per server
  README.md
  atomics/T1112/T1112.yaml
Labels: windows

#2504 T1547.005
  atomics/T1547.005/T1547.005.yaml
Labels: windows

#2481 Update T1562.001.yaml
  atomics/T1562.001/T1562.001.yaml
  atomics/T1562.008/T1562.008.yaml
Labels: cloud

#2478 Create T1098.003.yaml
  atomics/T1098.003/T1098.003.yaml
Labels: ADFS

#2509 Customshellhost
  atomics/T1218/T1218.yaml
Labels: windows

#2510 Update T1564.yaml
  atomics/T1564/T1564.yaml
Labels: windows

#2516 Update T1082.yaml
  atomics/T1082/T1082.yaml
Labels: windows
