Repository redcanaryco/atomic-red-team, pull requests merged in 2023-01, with the labels that each got.

#2263 corrected code so it will execute
  atomics/T1137.006/T1137.006.yaml
Labels: windows

#2234 T1082 list linux kernel modules - remove sudo
  atomics/T1082/T1082.yaml
Labels: linux

#2253 cleanup 1110.001 4 SUDO brute debian
  atomics/T1110.001/T1110.001.yaml
  atomics/T1110.001/src/asker.sh
Labels: linux

#2254 Added docker testcase for docker exec in T1609.yaml
  atomics/T1609/T1609.yaml
  atomics/T1609/src/dockerfile
Labels: containers

#2252 T1497.001 linux detect Virtualization - run both cmds
  atomics/T1497.001/T1497.001.yaml
Labels: linux

#2255 Added Deploying a docker
  atomics/T1610/T1610.yaml
  atomics/T1610/src/dockerfile
Labels: containers

#2273 add dll and prereqs
  atomics/T1137.002/T1137.002.yaml
  atomics/T1137.002/bin/officetest_x64.dll
  atomics/T1137.002/bin/officetest_x86.dll
  atomics/T1137.002/src/officetest/officetest.sln
  atomics/T1137.002/src/officetest/officetest/dllmain.cpp
  atomics/T1137.002/src/officetest/officetest/framework.h
  atomics/T1137.002/src/officetest/officetest/officetest.vcxproj
  atomics/T1137.002/src/officetest/officetest/officetest.vcxproj.filters
  atomics/T1137.002/src/officetest/officetest/officetest.vcxproj.user
  atomics/T1137.002/src/officetest/officetest/pch.cpp
  atomics/T1137.002/src/officetest/officetest/pch.h
  atomics/T1137.006/T1137.006.yaml
Labels: windows

#2274 Update T1562.001.yaml
  atomics/T1562.001/T1562.001.yaml
Labels: windows

#2269 add prereqs and simplify
  atomics/T1003.001/T1003.001.yaml
Labels: windows

#2284 T1059.004 New script file in the tmp directory
  atomics/T1059.004/T1059.004.yaml
Labels: linux
