Repository redcanaryco/atomic-red-team, pull requests merged in 2023-07, with the labels that each got.

#2479 Atomic Test #4 - RDP tunneling over Ngrok Cloud
  atomics/T1572/T1572.md
  atomics/T1572/T1572.yaml
Labels: windows

#2476 SMB over QUIC
  atomics/T1570/T1570.yaml
Labels: windows

#2485 Prakash22 k patch 1
  atomics/T1490/T1490.yaml
Labels: windows

#2484 Added test for T1547.012
  atomics/T1547.012/T1547.012.yaml
  atomics/T1547.012/bin/PrintProcessor.dll
  atomics/T1547.012/src/dllmain.cpp
Labels: windows

#2495 Create T1098.002.yaml
  atomics/T1098.002/T1098.002.yaml
Labels: cloud

#2490 T1547.012 - Fixed multiple issues with broken test
  atomics/T1547.012/T1547.012.yaml
  atomics/T1547.012/bin/AtomicTest.dll
  atomics/T1547.012/bin/PrintProcessor.dll
  atomics/T1547.012/src/AtomicTest.c
  atomics/T1547.012/src/AtomicTest.def
  atomics/T1547.012/src/build.bat
Labels: windows

#2498 Fix svg counter
  .github/workflows/generate-counter.yml
  bin/generate_counter.py
  poetry.lock
Labels: python

#2497 Fix Github action to generate labels for changed atomics
  .github/workflows/assign-labels.yml
  bin/generate_labels.py
Labels: python

#2491 Add new test "Port-Scanning /24 Subnet with PowerShell"
  atomics/T1046/T1046.yaml
Labels: windows

#2500 Modified description for Test 4
  atomics/T1560.001/T1560.001.yaml
Labels: linux, macOS, windows
