Repository redcanaryco/atomic-red-team, pull requests merged in 2023-10, with the labels that each got.

#2549 New Atomic Test: PromptOnSecureDesktop
  atomics/T1548.002/T1548.002.yaml
Labels: windows

#2539 T1055.011 - Process Injection: Extra Window Memory Injection
  .gitignore
  atomics/T1055.011/T1055.011.yaml
  atomics/T1055.011/bin/T1055.011_x64.exe
  atomics/T1055.011/bin/T1055.011_x86.exe
  atomics/T1055.011/bin/payload.exe_x64.bin
  atomics/T1055.011/bin/payload.exe_x86.bin
  atomics/T1055.011/bin/xbin.exe
  atomics/T1055.011/src/build_x64.bat
  atomics/T1055.011/src/build_x86.bat
  atomics/T1055.011/src/ewm.c
  atomics/T1055.011/src/ewm.h
  atomics/T1055.011/src/extrabytes_x64.txt
  atomics/T1055.011/src/extrabytes_x86.txt
  atomics/T1055.011/src/ntlib/ntddk.h
  atomics/T1055.011/src/ntlib/nttpp.h
  atomics/T1055.011/src/ntlib/util.h
  atomics/T1055.011/src/ntlib/x64/ntdll.lib
  atomics/T1055.011/src/ntlib/x86/ntdll.lib
  atomics/T1055.011/src/payload.c
  atomics/T1055.011/src/vsdevcmd_x64.bat
  atomics/T1055.011/src/vsdevcmd_x86.bat
  atomics/T1055.011/src/xbin.cpp
Labels: windows

#2552 correct url
  atomics/T1027/T1027.yaml
Labels: windows

#2531 Add T1056.002 GUI Input Capture macOS test
  atomics/T1056.002/T1056.002.yaml
Labels: macOS

#2556 fix typo
  atomics/T1036/T1036.yaml
Labels: windows

#2553 no prompt for confirmation
  atomics/T1021.001/T1021.001.yaml
Labels: windows

#2555 quote path
  atomics/T1027.004/T1027.004.yaml
Labels: windows

#2554 use external payloads directory
  atomics/T1027/T1027.yaml
Labels: windows

#2557 fix command
  atomics/T1047/T1047.yaml
Labels: windows

#2558 use cmd.exe syntax for temp dir
  atomics/T1059.007/T1059.007.yaml
Labels: windows

#2559 use command prompt
  atomics/T1069.001/T1069.001.yaml
Labels: windows

#2560 rearrange to have success exit code
  atomics/T1069.002/T1069.002.yaml
Labels: windows

#2568 Fix check dependency command
  atomics/T1555.003/T1555.003.md
  atomics/T1555.003/T1555.003.yaml
Labels: windows

#2561 use external payloads directory
  atomics/T1070.006/T1070.006.yaml
Labels: windows

#2562 xip.io to nip.io
  atomics/T1071.004/T1071.004.yaml
Labels: windows

#2563 catch failed download and exit
  atomics/T1003.001/T1003.001.yaml
Labels: windows

#2564 catch execution errors
  atomics/T1059.001/T1059.001.yaml
Labels: windows

#2565 exit code 0 on success
  atomics/T1003.002/T1003.002.yaml
Labels: windows

#2567 execute vbs with wscript
  atomics/T1036.003/T1036.003.yaml
Labels: windows

#2566 catch error and return exit code
  atomics/T1018/T1018.yaml
Labels: windows

#2569 Update T1059.004.yaml
  atomics/T1059.004/T1059.004.yaml
Labels: linux

#2573 Added initial test for technique T1553.003
  atomics/T1553.003/T1553.003.yaml
  atomics/T1553.003/bin/GTSIPProvider.dll
  atomics/T1553.003/src/GTSIPProvider.c
Labels: windows

#2571 Correct the capitalization in file names and remove blank lines
  atomics/T1552/T1552.md
  atomics/T1552/T1552.yaml
  atomics/T1555.003/T1555.003.md
Labels: linux, macOS, cloud

#2574 Added new tests that hides files through Powershell
  atomics/T1564.001/T1564.001.yaml
Labels: windows

#2576 Adding termsrv.dll path modification
  atomics/T1505.005/T1505.005.yaml
Labels: windows

#2570 Update T1562.001.yaml
  atomics/T1562.001/T1562.001.yaml
Labels: linux, macOS

#2578 Improve the getprereqs command
  atomics/T1027/T1027.md
  atomics/T1027/T1027.yaml
Labels: linux, macOS

#2580 fix prereqs
  atomics/T1048.002/T1048.002.yaml
Labels: windows
