Repository redcanaryco/atomic-red-team, pull requests merged in 2023-09, with the labels that each got.

#2517 Update T1021.001.yaml
  atomics/T1021.001/T1021.001.yaml
Labels: windows

#2521 Update T1564.004.yaml
  atomics/T1564.004/T1564.004.yaml
Labels: windows

#2520 Process injection dirty vanity
  atomics/T1055/T1055.yaml
  atomics/T1055/bin/x64/redVanity.exe
  atomics/T1055/src/x64/RedVanity/build.bat
  atomics/T1055/src/x64/RedVanity/redVanity.c
  atomics/T1055/src/x64/RedVanity/vanity.h
Labels: windows

#2515 Adding Simulate - Post BEC persistence via user password reset follow…
  atomics/T1098.003/T1098.003.yaml
Labels: cloud, ADFS

#2519 T1021.005 Apple Remote Desktop
  atomics/T1021.005/T1021.005.yaml
Labels: macOS

#2527 handle spaces in file path
  atomics/T1016/T1016.yaml
Labels: windows

#2524 T1055.002 Process Injection: (Fileless) Portable Executable Injection
  atomics/T1055.002/T1055.002.md
  atomics/T1055.002/T1055.002.yaml
  atomics/T1055.002/bin/RedInjection.exe
  atomics/T1055.002/src/RedInjection.c
  atomics/T1055.002/src/build.bat
Labels: windows

#2523 T1567.003
  atomics/T1567.003/T1567.003.yaml
Labels: windows

#2529 T1564.003 - Headless Browser Mockbin
  atomics/T1564.003/T1564.003.yaml
Labels: windows

#2533 fixed some path errors
  atomics/T1003.001/T1003.001.yaml
  atomics/T1083/T1083.yaml
Labels: windows

#2534 Modify Internet Zone Protocol Defaults in Current User Registry - powershell
  atomics/T1112/T1112.yaml
Labels: windows

#2532 T1005
  atomics/T1005/T1005.yaml
Labels: windows

#2536 updated lazagne URL
  atomics/T1555.003/T1555.003.md
  atomics/T1555.003/T1555.003.yaml
Labels: windows

#2538 use ExternalPayloads folder
  atomics/T1003/T1003.yaml
  atomics/T1036/T1036.yaml
Labels: windows

#2542 Update T1036.yaml
  atomics/T1036/T1036.yaml
Labels: windows

#2543 Download Directory creation
  atomics/T1003.002/T1003.002.yaml
Labels: windows

#2544 New ExternalPayloads dir creation
  atomics/T1110.004/T1110.004.yaml
Labels: windows

#2541 Fix T1083-6 DirLister PreReqs
  atomics/T1083/T1083.yaml
Labels: windows

#2545 Added ExternalPayloads directory
  atomics/T1027/T1027.yaml
  atomics/T1110.001/T1110.001.yaml
  atomics/T1110.003/T1110.003.yaml
  atomics/T1555.003/T1555.003.yaml
Labels: windows

#2546 Provlaunch.exe Executes Arbitrary Command via Registry Key
  atomics/T1218/T1218.yaml
Labels: windows

#2547 Added new tests for techniques T1082 and T1070
  atomics/T1070/T1070.yaml
  atomics/T1082/T1082.yaml
Labels: windows

#2548 adding test simulating DarkGate malware writing script to file from cmd
  README.md
  atomics/T1059.003/T1059.003.yaml
Labels: windows
