Repository redcanaryco/atomic-red-team, pull requests merged in 2023-02, with the labels that each got.

#2317 fix: Fix unescaped backslash in description
  atomic_red_team/atomic_doc_template.md.erb
Labels: enhancement

#2318 fix: Fixing index file names by removing colon and replacing with underscore
  bin/generate-atomic-docs.rb
Labels: bug

#2319 fix: Removing index files with colons
  atomics/Indexes/iaas:aws-index.yaml
  atomics/Indexes/iaas:azure-index.yaml
  atomics/Indexes/iaas:gcp-index.yaml
Labels: bug

#2320 fix: Adding missing index files
  atomics/Indexes/iaas_aws-index.yaml
  atomics/Indexes/iaas_azure-index.yaml
  atomics/Indexes/iaas_gcp-index.yaml
Labels: bug

#2304 T1552.007 Kubernetes list all secrets
  atomics/T1552.007/T1552.007.yaml
Labels: containers, !!

#2301 T1059.004 - Added four tests
  atomics/T1059.004/T1059.004.yaml
Labels: linux

#2313 T1546.004 added three tests
  atomics/T1546.004/T1546.004.yaml
Labels: linux

#2322 ci: Updating duration for stale issues before they close.
  .github/workflows/stale.yml
Labels: enhancement, maintainers

#2330 fix: Updating format of 2 yaml defintions for new schema
  atomics/T1048/T1048.yaml
  atomics/T1059.006/T1059.006.yaml
Labels: bug

#2307 Duplicate: Container and Resource Discovery
  atomics/T1613/T1613.yaml
  atomics/T1613/src/Dockerfile
Labels: containers

#2316 T1614.001: Add discovery tests for linux
  atomics/T1614.001/T1614.001.yaml
Labels: linux

#2326 Added two new tests to T1548.001
  atomics/T1548.001/T1548.001.yaml
Labels: linux

#2325 T1059.004 Added two tests
  atomics/T1059.004/T1059.004.yaml
Labels: linux

#2185 Terraform Proposal
  .github/workflows/validate-atomics.yml
  .gitignore
  atomics/T1562.008/T1562.008.yaml
  atomics/T1562.008/src/T1562.008-1/T1562.008-1.tf
  atomics/T1562.008/src/T1562.008-1/policy.json
  atomics/T1562.008/src/T1562.008-1/terraform.tfvars
  atomics/T1562.008/src/T1562.008-2/T1562.008-2.tf
  atomics/T1562.008/src/T1562.008-2/terraform.tfvars
Labels: cloud, !!

#2331 Update T1562.001.yaml
  atomics/T1562.001/T1562.001.yaml
Labels: linux

#2340 Use -Filter instead of Where-Object to improve perf and avoid missed items
  atomics/T1098/T1098.yaml
Labels: cloud

#2341 Improvements to "Azure AD - adding permission to application"
  atomics/T1098/T1098.yaml
Labels: cloud

#2346 T1112 - Added Event Viewer persistence tests
  atomics/T1112/T1112.yaml
Labels: windows

#2342 Adding Data Encrypted with GPG4Win
  atomics/T1486/T1486.yaml
Labels: windows

#2314 Begin T1580 Coverage - AWS
  atomics/T1580/T1580.yaml
Labels: cloud
