Repository redcanaryco/atomic-red-team, pull requests merged in 2023-04, with the labels that each got.

#2375 T1612 1
  atomics/T1612/T1612.yaml
  atomics/T1612/src/Dockerfile
  atomics/T1612/src/test.sh
Labels: containers, !!

#2393 T1562.003 added five tests (Linux)
  atomics/T1562.003/T1562.003.yaml
Labels: linux

#2376 T1046 -
  atomics/T1046/T1046.yaml
  atomics/T1046/src/Dockerfile
  atomics/T1046/src/scan.sh
Labels: containers

#2395 T1069.001 -added containers as platform
  atomics/T1069.001/T1069.001.yaml
  atomics/T1069.001/src/Dockerfile
  atomics/T1069.001/src/test.sh
Labels: containers

#2377 Added new test - macOS T1078.001
  atomics/T1078.001/T1078.001.yaml
Labels: macOS

#2398 T1552.001.yaml
  atomics/T1552.001/T1552.001.yaml
Labels: linux, cloud

#2343 T1059.004 Added Detecting pipe-to-shell
  atomics/T1059.004/T1059.004.yaml
  atomics/T1059.004/src/pipe-to-shell.sh
Labels: linux

#2345 T1546.004 Create/Append to .bash_logout
  atomics/T1546.004/T1546.004.yaml
Labels: linux

#2394 T1078.003 added three tests (Linux)
  atomics/T1078.003/T1078.003.yaml
Labels: linux

#2408 Tccontre redline defense evasion through registry
  atomics/T1112/T1112.yaml
Labels: windows
