Repository redcanaryco/atomic-red-team, pull requests merged in 2024-02, with the labels that each got.

#2679 Mikoyan dee patch 1
  atomics/T1040/T1040.yaml
Labels: windows

#2677 Update T1490.yaml
  atomics/T1490/T1490.yaml
Labels: windows

#2680 Improved Atomic Consistency with Python and pip Installation
  atomics/T1003.001/T1003.001.yaml
  atomics/T1018/T1018.yaml
  atomics/T1046/T1046.yaml
Labels: windows

#2673 T1027.007 Obfuscated Files or Information: Dynamic API Resolution: ninja syscall
  atomics/T1027.007/T1027.007.yaml
  atomics/T1027.007/bin/ninja_syscall1.exe
  atomics/T1027.007/src/build.bat
  atomics/T1027.007/src/ninja_syscall1.c
Labels: windows

#2674 Add new atomic test T1055 custom uuid process injection in C
  atomics/T1055/T1055.yaml
  atomics/T1055/bin/x64/uuid_injection.exe
  atomics/T1055/src/x64/uuidInjection/uuid_injection.c
Labels: windows

#2683 Adding ASR rules deletion
  atomics/T1562.001/T1562.001.yaml
Labels: linux, macOS

#2689 SOAPHound
  atomics/T1059.001/T1059.001.yaml
  atomics/T1059.001/bin/SOAPHound.exe
Labels: windows

#2690 New test: T1003.003 - Create Volume Shadow Copy with diskshadow
  atomics/T1003.003/T1003.003.yaml
  atomics/T1003.003/src/diskshadow.txt
Labels: windows

#2694 New Test T1137.001 - 'Office Application Startup: Office Template Macros.'
  atomics/T1137.001/T1137.001.yaml
Labels: windows

#2678 New test: T1218.011 Gamarue tradecraft commandline with rundll32 execution
  atomics/T1218.011/T1218.011.yaml
  atomics/T1218.011/bin/_WT.init
Labels: windows

#2696 Fix Github Actions
  atomics/T1110.001/T1110.001.yaml
  atomics/T1560.001/T1560.001.yaml
  atomics/T1562.004/T1562.004.yaml
Labels: bug

#2704 Adding new test for T1654 for Enumerate Windows Security Log
  atomics/T1654/T1654.yaml
Labels: windows

#2658 Update T1030.yaml Network-Based Data Transfer in Small Chunks
  atomics/T1030/T1030.yaml
Labels: linux, macOS, windows

#2706 Update RustDesk T1219.yaml
  atomics/T1219/T1219.yaml
Labels: windows

#2709 Update T1112.yaml
  atomics/T1112/T1112.yaml
Labels: windows

#2710 Update T1120.yaml
  atomics/T1120/T1120.yaml
Labels: windows

#2711 Adding T1134.001 Test 5 - JuicyPotato
  atomics/T1134.001/T1134.001.yaml
Labels: windows
