Repository redcanaryco/atomic-red-team, pull requests merged in 2024-12, with the labels that each got.

#2994 New Atomic - Exfiltrate Data using DNS Queries via dig
  atomics/T1048/T1048.yaml
Labels: linux, macOS

#3011 New Atomic - Clear PowerShell Session History
  atomics/T1070.003/T1070.003.yaml
Labels: windows

#3004 Expand ESXi-focused Tests
  atomics/T1021.004/T1021.004.yaml
  atomics/T1087.001/T1087.001.yaml
  atomics/T1485/T1485.yaml
  atomics/T1491.001/T1491.001.yaml
  atomics/T1529/T1529.yaml
  atomics/T1562.004/T1562.004.yaml
Labels: windows

#3005 Update T1486.yaml
  atomics/T1486/T1486.yaml
Labels: windows

#3006 SDDL Tampering Atomics
  atomics/T1222.001/T1222.001.yaml
  atomics/T1562.002/T1562.002.yaml
Labels: windows

#2999 Update broken uBlockLite URL
  atomics/T1176/T1176.md
  atomics/T1176/T1176.yaml
Labels: linux, macOS, windows

#3010 COMPlus_ETWEnabled Atomics
  atomics/T1562.006/T1562.006.yaml
Labels: windows

#3014 Autlogger Tampering Atomics
  atomics/T1562.001/T1562.001.yaml
Labels: macOS, windows

#3018 feat: more cloud credential discovery
  atomics/T1552.001/T1552.001.yaml
Labels: linux, macOS

#3017 Fix T1547.001 test b051b3c0-66e7-4a81-916d-e6383bd3a669 by adding /f argument to the reg modification by reg.exe
  atomics/T1547.001/T1547.001.yaml
Labels: windows

#3015 Update T1082.yaml
  atomics/T1082/T1082.yaml
Labels: windows

#3016 Update T1124.yaml
  atomics/T1124/T1124.yaml
Labels: windows
