Repository redcanaryco/atomic-red-team, pull requests merged in 2024-11, with the labels that each got.

#2963 Improve T1090.001
  atomics/T1090.001/T1090.001.yaml
Labels: linux, macOS

#2966 T1566.002 New - Paste and Run Technique
  atomics/T1566.002/T1566.002.yaml
Labels: windows

#2969 New atomic added.
  atomics/T1082/T1082.yaml
Labels: windows

#2970 New atomic added.
  atomics/T1082/T1082.yaml
Labels: windows

#2964 Improve T1562.003
  atomics/T1562.003/T1562.003.yaml
Labels: linux

#2973 Get Printer Device List via PowerShell Command
  atomics/T1120/T1120.yaml
Labels: windows

#2974 Move a T1036.003 test to T1036.007
  atomics/T1036.003/T1036.003.yaml
  atomics/T1036.007/T1036.007.yaml
  atomics/T1036.007/src/T1036.007_masquerading.ps1
  atomics/T1036.007/src/T1036.007_masquerading.vbs
Labels: windows

#2981 RunMRU Atomic Test
  atomics/T1202/T1202.yaml
Labels: windows

#2983 T1105 - Windows push file using scp.exe
  atomics/T1105/T1105.yaml
Labels: windows

#2989 Fix T1555
  atomics/T1555/T1555.yaml
Labels: windows

#2986 T1105 - Windows push file using sftp.exe
  atomics/T1105/T1105.yaml
Labels: linux, macOS, windows

#2980 Add tests to T1222
  atomics/T1222/T1222.yaml
Labels: windows

#2982 Update T1078.004.yaml
  atomics/T1078.004/T1078.004.yaml
  atomics/T1078.004/src/T1078.004-2/terraform.tfvars
Labels: cloud

#2992 New Atomic - Privilege Escalation via Docker Volume Mapping
  atomics/T1611/T1611.yaml
Labels: containers, !!
