Repository redcanaryco/atomic-red-team, pull requests merged in 2024-07, with the labels that each got.

#2800 Update T1489 - Add Linux tests
  atomics/T1489/T1489.yaml
Labels: linux

#2755 T1037.005, T1543.001, T1543.004 Persist Tests Enhancements
  atomics/T1037.005/T1037.005.yaml
  atomics/T1037.005/src/StartupParameters.plist
  atomics/T1037.005/src/T1037.005_agent.sh
  atomics/T1037.005/src/T1037.005_daemon.sh
  atomics/T1037.005/src/T1037_005_agent.plist
  atomics/T1037.005/src/T1037_005_daemon.plist
  atomics/T1543.001/T1543.001.yaml
  atomics/T1543.004/T1543.004.yaml
Labels: macOS

#2832 [CI/CD] Update assign-labels.yml
  .github/workflows/validate-atomics.yml
Labels: bug

#2830 Added new test to T1614.001.yaml
  atomics/T1614.001/T1614.001.yaml
Labels: windows

#2826 Update T1003.002.yaml
  atomics/T1003.002/T1003.002.yaml
Labels: windows

#2835 Update T1003.004.yaml
  atomics/T1003.004/T1003.004.yaml
Labels: windows

#2837 Adding more YAML validations
  .github/workflows/run-python-tests.yml
  .gitignore
  atomic_red_team/models.py
  atomic_red_team/runner.py
  atomic_red_team/test_data/empty_dependency_executor_name.yaml
  atomic_red_team/test_data/empty_input_arguments.yaml
  atomic_red_team/test_data/int_parsing.yaml
  atomics/T1112/T1112.yaml
  atomics/T1202/T1202.yaml
  atomics/T1218.011/T1218.011.yaml
  atomics/T1652/T1652.yaml
Labels: windows

#2841 Update T1012.yaml
  atomics/T1012/T1012.yaml
Labels: windows

#2827 Update T1113.yaml
  atomics/T1113/T1113.yaml
Labels: windows

#2806 Update T1048.md
  atomics/T1048/T1048.md
  atomics/T1048/T1048.yaml
Labels: windows

#2849 Added input argument #{host} to T1059.004
  atomics/T1059.004/T1059.004.yaml
Labels: linux, macOS

#2842 Update T1552.001.yaml
  atomics/T1552.001/T1552.001.yaml
Labels: windows

#2846 Fix System log file deletion via find utility scenario in T1070.002
  atomics/T1070.002/T1070.002.md
  atomics/T1070.002/T1070.002.yaml
Labels: macOS

#2847 Update T1070.002.yaml
  atomics/T1070.002/T1070.002.yaml
Labels: macOS

#2840 Update T1059.004.yaml
  atomics/T1059.004/T1059.004.yaml
Labels: linux, macOS

#2852 Fix T1070.003 & T1082
  atomic_red_team/models.py
  atomic_red_team/test_data/elevation_required_but_not_provided.yaml
  atomic_red_team/validator.py
  atomics/T1070.003/T1070.003.yaml
  atomics/T1082/T1082.yaml
Labels: linux

#2854 Update T1547.001.yaml
  atomics/T1547.001/T1547.001.yaml
Labels: windows

#2853 Fix ESXi tests
  atomics/T1078.001/T1078.001.yaml
  atomics/T1082/T1082.yaml
  atomics/T1083/T1083.yaml
  atomics/T1529/T1529.yaml
  atomics/T1562.010/T1562.010.yaml
Labels: macOS, windows

#2856 Update T1547.001.yaml
  atomics/T1547.001/T1547.001.yaml
Labels: windows

#2860 Update T1556.002.yaml
  atomics/T1556.002/T1556.002.yaml
Labels: windows

#2862 Update T1112.yaml
  atomics/T1112/T1112.yaml
Labels: windows

#2851 T1048.002
  atomics/T1048.002/T1048.002.yaml
Labels: linux

#2857 Added new test to T1614.001 "Discover System Language by Windows API …
  atomics/T1614.001/T1614.001.yaml
  atomics/T1614.001/bin/LanguageKeyboardLayout.exe
  atomics/T1614.001/src/LanguageKeyboardLayout.cs
Labels: windows

#2861 New Test - Modify RDP-Tcp Initial Program Registry Entry
  atomics/T1112/T1112.yaml
Labels: windows

#2863 3 new tests added
  atomics/T1112/T1112.yaml
Labels: windows

#2865 New Test - Adding custom debugger for Windows Error Reporting
  atomics/T1546/T1546.yaml
Labels: windows

#2867 Update T1078.003.yaml
  atomics/T1078.003/T1078.003.yaml
Labels: windows

#2869 Pipe Creation - PsExec Tool Execution From Suspicious Locations
  atomics/T1569.002/T1569.002.yaml
Labels: windows

#2870 Update T1112.yaml
  atomics/T1112/T1112.yaml
Labels: windows

#2855 Update T1218.yaml
  atomics/T1218/T1218.yaml
Labels: windows

#2876 Update T1217.yaml
  atomics/T1217/T1217.yaml
Labels: macOS, windows

#2875 Update T1547.yaml
  atomics/T1547/T1547.yaml
Labels: windows

#2877 New Test Added : Phantom Dll Hijacking - WinAppXRT.dll
  atomics/T1574.001/T1574.001.yaml
Labels: windows

#2878 Update T1546.008.yaml
  atomics/T1546.008/T1546.008.yaml
Labels: windows
