Repository redcanaryco/atomic-red-team, pull requests merged in 2024-03, with the labels that each got.

#2713 Fix T1071.001 Test #2
  atomics/T1071.001/T1071.001.md
  atomics/T1071.001/T1071.001.yaml
Labels: windows

#2714 New test: T1542.001 - 'UEFI Persistence via Wpbbin.exe File Creation'
  atomics/T1542.001/T1542.001.yaml
Labels: windows

#2695 New Tests: T1001.002 - Data Obfuscation: Steganography
  atomics/T1001.002/T1001.002.yaml
Labels: windows

#2716 Update T1562.003.yaml
  atomics/T1562.003/T1562.003.yaml
Labels: linux, windows

#2717 Update T1562.003.yaml
  atomics/T1562.003/T1562.003.yaml
Labels: windows

#2722 Update T1070.003.yaml
  atomics/T1070.003/T1070.003.yaml
Labels: linux

#2659 Update T1580.yaml AWS - EC2 Security Group Enumeration
  atomics/T1580/T1580.yaml
Labels: linux, macOS, cloud

#2719 Rundll32 FileProtocolHandler Command Execution Evasion add new sub-technique to T1218.011
  atomics/T1218.011/T1218.011.yaml
Labels: windows

#2715 Added a new atomic to T1202
  atomics/T1105/T1105.yaml
  atomics/T1105/bin/GUP.exe
  atomics/T1105/bin/gup.xml
  atomics/T1105/bin/libcurl.dll
Labels: windows

#2718 Add test 24 to T1562.004
  atomics/T1562.004/T1562.004.yaml
Labels: windows

#2662 Update T1072.yaml Deploy 7-Zip Using Chocolatey
  atomics/T1072/T1072.yaml
Labels: windows

#2726 Update T1569.001.yaml: Fixed description for label_name
  atomics/T1569.001/T1569.001.yaml
Labels: macOS

#2728 force delete
  atomics/T1112/T1112.yaml
Labels: windows

#2732 Fix nonstandard capitalization in "type" field
  atomics/T1071/T1071.yaml
Labels: windows

#2730 Added new atomic test: Update T1001.002.yaml
  atomics/T1001.002/T1001.002.yaml
Labels: linux, windows
