Repository redcanaryco/atomic-red-team, pull requests merged in 2024-09, with the labels that each got.

#2923 Fix `T1135.yaml`
  atomics/T1135/T1135.yaml
Labels: linux

#2924 Fix `T1056.001.yaml`
  atomics/T1056.001/T1056.001.yaml
Labels: linux

#2922 Fix `T1078.003.yaml`
  atomics/T1078.003/T1078.003.yaml
Labels: linux

#2925 Fix `T1070.004.yaml`
  atomics/T1070.004/T1070.004.yaml
Labels: linux

#2926 Fix `T1543.002.yaml`
  atomics/T1543.002/T1543.002.yaml
Labels: linux

#2897 Update T1546.yaml
  atomics/T1546/T1546.yaml
Labels: windows

#2927 Fix `T1560.001.yaml`
  atomics/T1560.001/T1560.001.yaml
Labels: linux, macOS

#2928 Update T1016.001.yaml
  atomics/T1016.001/T1016.001.yaml
Labels: windows

#2936 Fix Test `T1070.003.yaml`
  atomics/T1070.003/T1070.003.yaml
Labels: linux, macOS

#2935 Fix test `T1105.yaml`
  atomics/T1105/T1105.yaml
Labels: linux, macOS

#2931 Fixing test `T1110.001.yaml`
  atomics/T1110.001/T1110.001.yaml
Labels: linux, windows

#2932 Fix test `T1078.003.yaml`
  atomics/T1078.003/T1078.003.yaml
Labels: linux

#2930 Fixing test `T1546.004.yaml`
  atomics/T1546.004/T1546.004.yaml
Labels: linux

#2943 Fixing test `T1562.004.yaml`
  atomics/T1562.004/T1562.004.yaml
Labels: linux

#2941 Create T1497.003.yaml
  atomics/T1497.003/T1497.003.yaml
Labels: linux, macOS

#2945 Update T1036.004.yaml
  atomics/T1036.004/T1036.004.yaml
Labels: linux

#2937 CompMgmt.msc to Calc
  atomics/T1053.005/T1053.005.yaml
Labels: windows

#2940 Uac bypassed via prog i ds
  atomics/T1548.002/T1548.002.yaml
Labels: windows

#2911 Btops140824
  atomics/T1012/T1012.yaml
  atomics/T1057/T1057.yaml
  atomics/T1070.004/T1070.004.yaml
  atomics/T1222/T1222.yaml
Labels: windows

#2902 Blueteam0ps 31072024
  atomics/T1105/T1105.yaml
  atomics/T1560.001/T1560.001.yaml
  atomics/T1564.008/T1564.008.yaml
Labels: windows, ADFS

#2948 Fix a typo in T1082 - Linux VM Check via Hardware
  atomics/T1082/T1082.yaml
Labels: linux
