Repository redcanaryco/atomic-red-team, pull requests merged in 2024-04, with the labels that each got.

#2733 Added new atomic test: Update T1490.yaml
  atomics/T1490/T1490.yaml
Labels: macOS

#2734 Added new atomic test: Update T1105.yaml
  atomics/T1105/T1105.yaml
Labels: macOS

#2731 Create T1114.002.yaml
  atomics/T1114.002/T1114.002.yaml
Labels: cloud

#2738 Atomics & Code Cleanup
  .github/workflows/validate-atomics.yml
  .github/workflows/validate-terraform.yml
  atomic_red_team/atomic_test_template.yaml
  atomic_red_team/spec.yaml
  atomics/T1071/T1071.yaml
  atomics/T1090.001/T1090.001.yaml
  atomics/T1547.006/T1547.006.yaml
Labels: linux, macOS, windows

#2742 Update T1562.003.yaml
  atomics/T1562.003/T1562.003.yaml
Labels: windows

#2744 Bug fix: Removed 'pause' from T1082 Seatbelt atomic that causes timeout
  atomics/T1082/T1082.yaml
Labels: windows

#2745 Adding T1135 Test 11 - Enumerate All Network Shares with SharpShares
  atomics/T1135/T1135.yaml
Labels: windows

#2752 Create T1622.yaml
  atomics/T1622/T1622.yaml
Labels: windows

#2757 Fix auto_generated_guids file
  atomic_red_team/guid.py
  atomics/used_guids.txt
Labels: bug

#2743 Added tests for T1562.012
  atomics/T1562.012/T1562.012.yaml
Labels: linux

#2741 Update T1048.002.yaml
  atomics/T1048.002/T1048.002.yaml
Labels: linux

#2759 Add tests for python code
  .github/workflows/generate-counter.yml
  .github/workflows/generate-docs.yml
  .github/workflows/run-python-tests.yml
  .github/workflows/validate-atomics.yml
  atomic_red_team/guid.py
  atomic_red_team/runner.py
  atomic_red_team/test_data/float_type.yaml
  atomic_red_team/test_data/int_type.yaml
  atomic_red_team/test_data/invalid_directory/.gitkeep
  atomic_red_team/test_data/invalid_filename.yml
  atomic_red_team/test_data/missing_input_argument.yaml
  atomic_red_team/test_data/reused_guid.yaml
  atomic_red_team/test_data/string_pattern_mismatch.yaml
  atomic_red_team/test_data/string_too_short.yaml
  atomic_red_team/test_data/unused_input_argument.yaml
  atomic_red_team/test_data/url_parsing.yaml
  atomic_red_team/tests/__init__.py
  atomic_red_team/tests/test_models.py
  atomic_red_team/tests/test_validate.py
  atomic_red_team/validator.py
  poetry.lock
  pyproject.toml
Labels: python

#2748 Adding T1112 Test 69
  atomics/T1112/T1112.yaml
Labels: windows

#2758 Added new a new atomic test in T1003 and T1187
  atomics/T1003/T1003.yaml
  atomics/T1187/T1187.yaml
Labels: windows
