Repository redcanaryco/atomic-red-team, pull requests merged in 2024-08, with the labels that each got.

#2871 Update T1059.004.yaml
  atomics/T1059.004/T1059.004.yaml
Labels: linux, macOS

#2888 Update T1562.008.yaml
  atomics/T1562.008/T1562.008.yaml
Labels: linux, macOS, cloud

#2887 Fix T1612.yaml
  atomics/T1612/T1612.yaml
Labels: containers

#2886 Fix T1613.yaml
  atomics/T1613/T1613.yaml
  atomics/T1613/src/Dockerfile
Labels: containers

#2892 Fix 1046.yaml
  atomics/T1046/T1046.yaml
Labels: containers

#2880 Update T1546.yaml
  atomics/T1546/T1546.yaml
Labels: windows

#2881 Update T1574.002.yaml
  atomics/T1574.002/T1574.002.yaml
Labels: windows

#2882 New Test : Leverage Virtual Channels to execute custom DLL during successful RDP session
  atomics/T1547/T1547.yaml
Labels: windows

#2883 Update T1546.yaml
  atomics/T1546/T1546.yaml
Labels: windows

#2884 Update T1564.003.yaml
  atomics/T1564.003/T1564.003.yaml
Labels: windows

#2895 Update T1082.yaml
  atomics/T1082/T1082.yaml
Labels: windows

#2894 Update T1059.004.yaml
  atomics/T1059.004/T1059.004.yaml
Labels: linux, macOS

#2891 Fix T1003.008.yaml
  atomics/T1003.008/T1003.008.yaml
Labels: linux

#2893 Fix T1543.002.yaml
  atomics/T1543.002/T1543.002.yaml
Labels: linux

#2898 Update T1574.001.yaml - New Test Added - Phantom Dll Hijacking - ualapi.dll
  atomics/T1574.001/T1574.001.yaml
Labels: windows

#2899 Update T1546.yaml - New Test - Persistence using STARTUP-PATH in MS-WORD
  atomics/T1546/T1546.yaml
Labels: windows

#2901 Creation of T1614.yaml and T1016.001.yaml
  atomics/T1016.001/T1016.001
  atomics/T1614/T1614.yaml
Labels: linux, macOS, windows

#2909 Update typo and small grammar details in T1071.yaml
  atomics/T1071/T1071.yaml
Labels: windows
