Repository redcanaryco/atomic-red-team, pull requests merged in 2024-10, with the labels that each got.

#2939 Uac bypassed and persistence
  atomics/T1053.005/T1053.005.yaml
Labels: windows

#2955 Update T1082.yaml
  atomics/T1082/T1082.yaml
Labels: windows

#2950 T1486 Improvements
  atomics/T1486/T1486.yaml
Labels: linux

#2956 Update T1082.yaml
  atomics/T1082/T1082.yaml
Labels: windows

#2958 Update T1007.yaml
  atomics/T1007/T1007.yaml
Labels: windows

#2961 Update T1003.001.yaml
  atomics/T1003.001/T1003.001.yaml
Labels: windows

#2959 Update T1012.yaml
  atomics/T1012/T1012.yaml
Labels: windows

#2962 Create T1025.yaml
  atomics/T1025/T1025.yaml
Labels: windows

#2965 Add new atomic - T1518.001.yaml
  atomics/T1518.001/T1518.001.yaml
Labels: windows, !!
