Repository redcanaryco/atomic-red-team, pull requests merged in 2025-02, with the labels that each got.

#3047 T1046 - added csv option to ip_address parameter to test number 10
  atomics/T1046/T1046.yaml
Labels: windows, 5 min review

#3048 T1555.001 Copy Keychain via cat
  atomics/T1555.001/T1555.001.yaml
Labels: macOS, 1 min review

#3049 Update the ATT&CK Navigator Layers to v16
  README.md
  bin/generate-atomic-docs.rb
Labels: 1 min review

#3050 T1539 AppleScript Copying Safari Cookies test
  atomics/T1539/T1539.yaml
Labels: macOS, windows, 1 min review

#3051 T1005 Test to Copy Apple Notes Databases via AppleScript
  atomics/T1005/T1005.yaml
Labels: linux, macOS, 1 min review

#3058 fix MD->HTML render for .io site
  atomic_red_team/atomic_doc_template.md.erb
Labels: 1 min review

#3057 feat: T1567.002 test 2
  atomics/T1567.002/T1567.002.yaml
  atomics/T1567.002/src/main.tf
  atomics/T1567.002/src/output.tf
  atomics/T1567.002/src/storage.tf
  atomics/T1567.002/src/variables.tf
Labels: linux, macOS, 5 min review

#3060 Update T1136.003.yaml
  atomics/T1136.003/T1136.003.yaml
Labels: ADFS, 1 min review

#3044 Create T1059.010.yaml
  atomics/T1059.010/T1059.010.yaml
  atomics/T1059.010/src/calc.ahk
Labels: windows, 5 min review

#3065 add elevation required
  atomics/T1553.005/T1553.005.yaml
Labels: windows, 1 min review

#3061 Fixes #2967
  atomics/T1486/T1486.yaml
Labels: windows, 1 min review

#3064 Create T1036.003_masquerading.vbs
  atomics/T1036.003/src/T1036.003_masquerading.vbs
Labels: 1 min review

#3066 avoid command hanging
  atomics/T1555.003/T1555.003.yaml
Labels: windows, 1 min review

#3063 Added T1095 for Linux
  atomics/T1095/T1095.yaml
Labels: linux

#3056 Fix some mistake in T1560.002 and T1016.001
  atomics/T1016.001/T1016.001.md
  atomics/T1016.001/T1016.001.yaml
  atomics/T1560.002/T1560.002.md
  atomics/T1560.002/T1560.002.yaml
Labels: linux, macOS, 1 min review
