Repository redcanaryco/atomic-red-team, pull requests merged in 2025-04, with the labels that each got.

#3095 Removed superfluous echo preventing T1553.004 from running update-ca-certificates
  atomics/T1553.004/T1553.004.md
  atomics/T1553.004/T1553.004.yaml
Labels: linux, 1 min review

#3096 Update T1546.008.yaml - New Atomic Tests
  atomics/T1546.008/T1546.008.yaml
Labels: windows, 1 min review

#3094 Update T1218.005.yaml for windows 11 calculator
  atomics/T1218.005/T1218.005.yaml
Labels: windows, 1 min review

#3090 updated T1569.002 Use PsExec to execute a command on a remote host
  atomics/T1569.002/T1569.002.yaml
Labels: windows, 1 min review

#3093 Added four atomic tests for an Azure Function code injection scenario
  atomics/T1530/T1530.yaml
  atomics/T1550.001/T1550.001.yaml
  atomics/T1550.001/src/code_to_insert.py
  atomics/T1619/T1619.yaml
Labels: cloud, 5 min review

#3104 Update README.md
  README.md
Labels: N/A min review

#3101 Updated supported_platforms in the atomic regarding T1564.008
  atomics/T1564.008/T1564.008.yaml
Labels: cloud, 1 min review

#3103 Add T1578.001 - Cloud Snapshot Creation Tests (AWS, Azure, GCP)
  atomics/T1578.001/T1578.001.md
  atomics/T1578.001/T1578.001.yaml
Labels: cloud, 5 min review
