Repository redcanaryco/atomic-red-team, pull requests merged in 2025-01, with the labels that each got.

#3023 feat: T1526 discovery (AWS and Azure)
  atomics/T1526/T1526.yaml
  atomics/T1526/src/AWSDiscovery.ps1
  atomics/T1526/src/AzureDiscovery.ps1
Labels: cloud, 1 min review

#3025 New Atomic TestT1547.001.yaml
  atomics/T1547.001/T1547.001.yaml
Labels: windows, 1 min review

#3019 Added two new tests to T1614.001
  atomics/T1614.001/T1614.001.yaml
Labels: windows, 5 min review

#3027 feat: Added T1595.003
  atomics/T1595.003/T1595.003.yaml
  atomics/T1595.003/src/WebServerScan.ps1
  atomics/T1595.003/src/wordlist.txt
Labels: linux, macOS, windows, 1 min review

#3036 New T1539 Test for Chrome ABE Bypass via Remote Debugging
  atomics/T1539/T1539.yaml
Labels: macOS, windows, 5 min review

#3031 New Technique: T1651
  atomics/T1651/T1651.yaml
  atomics/T1651/src/T1651-1/AWSSSMAttack.ps1
  atomics/T1651/src/T1651-1/compute.tf
  atomics/T1651/src/T1651-1/main.tf
  atomics/T1651/src/T1651-1/network.tf
  atomics/T1651/src/T1651-1/output.tf
  atomics/T1651/src/T1651-1/security.tf
  atomics/T1651/src/T1651-1/variables.tf
Labels: cloud, 20 min review

#3040 Remove unused variable
  atomics/T1003.002/T1003.002.yaml
  atomics/T1046/T1046.yaml
  atomics/T1078.003/T1078.003.yaml
  atomics/T1082/T1082.yaml
  atomics/T1087.002/T1087.002.yaml
  atomics/T1110.003/T1110.003.yaml
  atomics/T1120/T1120.yaml
  atomics/T1135/T1135.yaml
  atomics/T1518/T1518.yaml
  atomics/T1548.002/T1548.002.yaml
  atomics/T1552.001/T1552.001.yaml
  atomics/T1555.003/T1555.003.yaml
  atomics/T1555/T1555.yaml
  atomics/T1558.003/T1558.003.yaml
  atomics/T1562.001/T1562.001.yaml
  atomics/T1615/T1615.yaml
  atomics/T1620/T1620.yaml
Labels: windows, 10 min review

#3041 Added additional tests for Virtualization/Sandbox Evasion: System Checks
  atomics/T1497.001/T1497.001.yaml
Labels: macOS, 5 min review

#3038 feat: T1648-1
  atomics/T1648/T1648.yaml
  atomics/T1648/src/T1648-1/LambdaAttack.ps1
  atomics/T1648/src/T1648-1/compute.tf
  atomics/T1648/src/T1648-1/iam.tf
  atomics/T1648/src/T1648-1/main.tf
  atomics/T1648/src/T1648-1/storage.tf
  atomics/T1648/src/T1648-1/variables.tf
Labels: cloud, 20 min review
