Repository redcanaryco/atomic-red-team, pull requests merged in 2025-03, with the labels that each got.

#3070 Update T1070.002.md
  atomics/T1070.002/T1070.002.md
  atomics/T1070.002/T1070.002.yaml
Labels: linux, 1 min review

#3068 Update T1219.yaml with Quick assist
  atomics/T1219/T1219.yaml
Labels: windows, 1 min review

#3069 Marthajsosa patch 1
  atomics/T1135/T1135.md
  atomics/T1135/T1135.yaml
Labels: windows, 1 min review

#3073 Fix: mistake in T1113-9
  atomics/T1113/T1113.yaml
Labels: windows, 1 min review

#3075 Fix: Get prereq T1562.004
  atomics/T1562.004/T1562.004.yaml
Labels: linux, 1 min review

#3074 feat: Add T1046-12
  atomics/T1046/T1046.yaml
Labels: linux, macOS, 1 min review

#3077 Remove Launch Daemon test in the user directory.
  atomics/T1543.004/T1543.004.yaml
Labels: 1 min review

#3078 Added devtunnels
  atomics/T1572/T1572.yaml
Labels: linux, macOS, 5 min review

#3079 Added VSCode tunnel
  atomics/T1572/T1572.yaml
Labels: linux, macOS, windows, 5 min review

#3080 Added Cloudlfare tunnel
  atomics/T1572/T1572.yaml
Labels: linux, macOS, 5 min review

#3087 Fix: small grammar/spelling errors in T1564.004
  atomics/T1564.004/T1564.004.yaml
Labels: windows, 1 min review

#3086 bump ScreenConnect version
  atomics/T1219/T1219.md
  atomics/T1219/T1219.yaml
Labels: windows, 1 min review

#3084 Update T1546.008.yaml - New Atomic Test
  atomics/T1546.008/T1546.008.yaml
Labels: windows, 1 min review

#3085 T1105- OneDriveStandaloneUpdater
  atomics/T1105/T1105.yaml
Labels: windows, 5 min review

#3081 Issue 3026: Remove single tick
  atomics/T1098.001/bin/aws_secret.sh
Labels: cloud, 1 min review
