Repository redcanaryco/atomic-red-team, pull requests merged in 2025-07, with the labels that each got.

#3142 Moved two atomics from T1550.001 to T1528
  atomics/T1528/T1528.yaml
  atomics/T1528/src/code_to_insert.py
  atomics/T1550.001/T1550.001.md
Labels: 5 min review

#3147 Update T1547.001.yaml
  atomics/T1547.001/T1547.001.yaml
Labels: windows, 1 min review

#3152 Add atomic test "Decrypt to file" to T1027.013.yaml
  atomics/T1027.013/T1027.013.yaml
Labels: linux, macOS, windows, 1 min review
