Repository redcanaryco/atomic-red-team, pull requests merged in 2025-10, with the labels that each got.

#3197 Identifying Network Shares - Linux
  atomics/T1083/T1083.yaml
Labels: linux, 1 min review

#3192 disable ASLR protection via sysctl
  atomics/T1562.001/T1562.001.yaml
Labels: windows, 1 min review

#3201 Fix Issue Template URL
  .github/ISSUE_TEMPLATE/new_atomic.md
Labels: 1 min review
